CREATE TABLE "table" (
	"id" serial,
	"A" integer,
	"B" integer,
	"C" integer,
	"D" integer,
	"E" integer,
	"F" integer,
	"G" integer,
	"H" integer,
	"I" integer,
	"J"	integer,
	"K"	integer,
	"L"	integer,
	"M"	integer,
	"N"	integer,
	"O"	integer,
	"P"	integer,
	"Q"	integer,
	"R"	integer,
	"S"	integer,
	"T"	integer,
	"U"	integer,
	"V"	integer,
	"W"	integer,
	"X"	integer,
	"Y"	integer,
	"Z"	integer,
	CONSTRAINT "table_pk" PRIMARY KEY ("id")
);
